#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
# shellcheck source=./sprint-parse.sh
source "${SCRIPT_DIR}/sprint-parse.sh"

# Parse arguments
PHASE="all"
SKIP_PER_MERGE_TEST=false
SKIP_HOOKS=false
for arg in "$@"; do
  case "$arg" in
    --phase) shift; PHASE="${1:-all}"; shift || true ;;
    1|2) PHASE="$arg" ;;
    --skip-per-merge-test) SKIP_PER_MERGE_TEST=true ;;
    --skip-hooks) SKIP_HOOKS=true ;;
  esac
done

# Select merge order based on phase
if [ "$PHASE" = "1" ]; then
  ACTIVE_MERGE=("${PHASE1_MERGE_ORDER[@]}")
  SKIP_PER_MERGE_TEST=true  # Phase 1 = new files only, safe to skip
elif [ "$PHASE" = "2" ]; then
  ACTIVE_MERGE=("${PHASE2_MERGE_ORDER[@]}")
else
  ACTIVE_MERGE=("${MERGE_ORDER[@]}")
fi

# Ephemeral files that always conflict between agents — auto-resolve with --theirs
EPHEMERAL_FILES=(
  "AGENT_BRIEF.md"
  ".claude-output.txt"
  "docs/project-memory/.index/last-updated.txt"
)

echo "=== Sprint ${SPRINT_NUM} Phase ${PHASE} — Merging ${#ACTIVE_MERGE[@]} branches ==="
echo ""
echo "Merge order:"
for i in "${!ACTIVE_MERGE[@]}"; do
  echo "  $((i+1)). ${ACTIVE_MERGE[$i]}"
done
echo ""
if $SKIP_PER_MERGE_TEST; then
  echo "Per-merge testing: SKIPPED (will run once after all merges)"
else
  echo "Verification after each merge:"
  for cmd in "${MERGE_VERIFY[@]}"; do
    echo "  - ${cmd}"
  done
fi
echo ""

# Confirm we're on main
CURRENT_BRANCH=$(git branch --show-current)
if [ "$CURRENT_BRANCH" != "main" ]; then
  echo "Error: Must be on main branch (currently on '${CURRENT_BRANCH}')"
  exit 1
fi

# Clean up ALL dirty .index files and ephemeral files that would block merges
# These are auto-generated by pre-commit hooks and safe to discard
git checkout -- docs/project-memory/.index/ 2>/dev/null || true
git clean -f docs/project-memory/.index/ 2>/dev/null || true
for ef in "${EPHEMERAL_FILES[@]}"; do
  git checkout -- "$ef" 2>/dev/null || true
done

## Deduplicate JSON files — after a merge, if both branches added the same key
## to a .json file, git keeps both (duplicate keys). Python's json.load keeps
## the last value for duplicate keys (per JSON spec), so round-tripping through
## json.load → json.dumps naturally deduplicates.
dedup_json_files() {
  local files=("$@")
  local changed=false
  for file in "${files[@]}"; do
    [ -f "$file" ] || continue
    # Only process if Python can parse it (skip non-JSON or broken files)
    if python3 -c "
import json, sys
f = sys.argv[1]
with open(f) as fh:
    d = json.load(fh)
with open(f, 'w') as fh:
    fh.write(json.dumps(d, indent=2) + '\n')
" "$file" 2>/dev/null; then
      if ! git diff --quiet -- "$file" 2>/dev/null; then
        git add "$file"
        changed=true
        echo "  [dedup] ${file} — normalized JSON (duplicate keys removed)"
      fi
    fi
  done
  if $changed; then
    git commit --amend --no-edit
  fi
}

MERGED=0
TOTAL=${#ACTIVE_MERGE[@]}

# Track per-agent merge results for PROJECT_STATUS
# Use temp directory instead of associative arrays (bash 3.x compat)
MERGE_DATA_DIR=$(mktemp -d)
trap 'rm -rf "$MERGE_DATA_DIR"' EXIT

for agent in "${ACTIVE_MERGE[@]}"; do
  MERGED=$((MERGED + 1))
  echo "=== [$MERGED/$TOTAL] Merging ${agent} ==="

  # Check branch exists
  if ! git rev-parse --verify "$agent" >/dev/null 2>&1; then
    echo "Error: Branch '${agent}' does not exist"
    exit 1
  fi

  # Capture agent commits before merge (for PROJECT_STATUS)
  git log --oneline "main..${agent}" -- 2>/dev/null | grep -v "^$" > "${MERGE_DATA_DIR}/${agent}.commits" || true

  # Capture file stats before merge
  git diff --shortstat "main...${agent}" 2>/dev/null > "${MERGE_DATA_DIR}/${agent}.stats" || true

  # Attempt merge
  if git merge "$agent" --no-edit 2>&1; then
    echo "[clean]   ${agent} merged without conflicts"
    echo "Clean" > "${MERGE_DATA_DIR}/${agent}.conflict"
  else
    echo "[conflict] Attempting auto-resolution of ephemeral files..."

    # Try to resolve known ephemeral file conflicts
    UNRESOLVED=false
    CONFLICT_FILES=()
    for file in $(git diff --name-only --diff-filter=U); do
      IS_EPHEMERAL=false
      for eph in "${EPHEMERAL_FILES[@]}"; do
        if [[ "$file" == "$eph" ]] || [[ "$file" == docs/project-memory/.index/* ]]; then
          IS_EPHEMERAL=true
          break
        fi
      done

      if $IS_EPHEMERAL; then
        git checkout --theirs "$file" 2>/dev/null && git add "$file"
        echo "  [auto]  ${file} — accepted theirs"
      elif $SKIP_PER_MERGE_TEST; then
        # Phase 1: earlier agent in merge order owns the file — keep ours
        git checkout --ours "$file" 2>/dev/null && git add "$file"
        echo "  [auto]  ${file} — file ownership conflict, kept ours (earlier agent)"
        CONFLICT_FILES+=("$file")
      else
        UNRESOLVED=true
        CONFLICT_FILES+=("$file")
        echo "  [MANUAL] ${file} — requires manual resolution"
      fi
    done

    if $UNRESOLVED; then
      echo ""
      echo "=== MERGE PAUSED ==="
      echo "Resolve the conflicts above, then run:"
      echo "  git add <resolved files>"
      echo "  git commit --no-edit"
      echo "  Re-run this script to continue with remaining merges."
      exit 1
    fi

    # All conflicts were ephemeral — commit
    git add docs/project-memory/.index/ 2>/dev/null || true
    git commit --no-edit

    # Record conflict details
    if [ ${#CONFLICT_FILES[@]} -gt 0 ]; then
      echo "${#CONFLICT_FILES[@]} conflicts (resolved: ${CONFLICT_FILES[*]})" > "${MERGE_DATA_DIR}/${agent}.conflict"
    else
      echo "Ephemeral only" > "${MERGE_DATA_DIR}/${agent}.conflict"
    fi
    echo "[resolved] ${agent} merged (ephemeral conflicts auto-resolved)"
  fi

  # Run verification after each merge (unless skipped)
  if ! $SKIP_PER_MERGE_TEST; then
    echo ""
    echo "--- Verification ---"
    for cmd in "${MERGE_VERIFY[@]}"; do
      echo "Running: ${cmd}"
      if eval "$cmd" 2>&1; then
        echo "[pass] ${cmd}"
      else
        echo ""
        echo "=== VERIFICATION FAILED ==="
        echo "Command failed: ${cmd}"
        echo "Branch ${agent} was merged but verification failed."
        echo "Fix the issue, commit, then continue with remaining merges."
        exit 1
      fi
      echo ""
    done
  fi

  # Dedup any JSON files modified by this merge
  json_files=()
  while IFS= read -r jf; do
    [ -n "$jf" ] && json_files+=("$jf")
  done < <(git diff --name-only HEAD~1 HEAD -- '*.json' 2>/dev/null || true)
  if [ ${#json_files[@]} -gt 0 ]; then
    dedup_json_files "${json_files[@]}"
  fi

  # ── Collect .sprint-findings.json if present ─────────────────────────────
  FINDINGS_DIR="${ROOT}/.sprint/findings"
  AGENT_WT="${SPRINT_BASE}/${agent}"
  FINDINGS_SRC=""
  # Try worktree first (still exists during merge phase)
  if [ -f "${AGENT_WT}/.sprint-findings.json" ]; then
    FINDINGS_SRC="${AGENT_WT}/.sprint-findings.json"
  # Fallback: check if it was committed in the branch
  elif git show "${agent}:.sprint-findings.json" >/dev/null 2>&1; then
    FINDINGS_SRC="__git_show__"
  fi
  if [ -n "$FINDINGS_SRC" ]; then
    mkdir -p "$FINDINGS_DIR"
    if [ "$FINDINGS_SRC" = "__git_show__" ]; then
      git show "${agent}:.sprint-findings.json" > "${FINDINGS_DIR}/${agent}.json"
    else
      cp "$FINDINGS_SRC" "${FINDINGS_DIR}/${agent}.json"
    fi
    echo "[findings] Collected .sprint-findings.json → .sprint/findings/${agent}.json"
  fi

  echo "[ok] ${agent} merged"
  echo ""
done

echo "========================================="
echo "  Sprint ${SPRINT_NUM} Phase ${PHASE} — All ${TOTAL} branches merged"
echo "========================================="
echo ""

# ─── Run final verification and capture output ──────────────────────────────
VERIFY_OUTPUT=""
run_and_capture_verify() {
  local label="$1"
  echo "--- ${label} ---"
  for cmd in "${MERGE_VERIFY[@]}"; do
    echo "Running: ${cmd}"
    local output
    if output=$(eval "$cmd" 2>&1); then
      echo "[pass] ${cmd}"
      VERIFY_OUTPUT="${VERIFY_OUTPUT}${output}"$'\n'
    else
      echo ""
      echo "=== VERIFICATION FAILED ==="
      echo "Command failed: ${cmd}"
      echo "$output"
      if [ "$label" = "Final Verification" ]; then
        echo "Fix the issue and commit before proceeding."
      else
        echo "Branch was merged but verification failed."
        echo "Fix the issue, commit, then continue with remaining merges."
      fi
      exit 1
    fi
    echo ""
  done
}

if $SKIP_PER_MERGE_TEST; then
  run_and_capture_verify "Final Verification"
fi

# Extract test count from verification output (supports common test frameworks)
TEST_COUNT=""
if [ -n "$VERIFY_OUTPUT" ]; then
  # Try: "N passed" (Playwright/Jest), "N tests" (Vitest), "N passed, N failed"
  TEST_COUNT=$(echo "$VERIFY_OUTPUT" | grep -oE '[0-9]+ passed' | tail -1 || true)
  if [ -z "$TEST_COUNT" ]; then
    TEST_COUNT=$(echo "$VERIFY_OUTPUT" | grep -oE '[0-9]+ tests?' | tail -1 || true)
  fi
fi

# Check build status if npm/npx is available and build script exists
BUILD_STATUS=""
if [ -f "${ROOT}/package.json" ] && grep -q '"build"' "${ROOT}/package.json" 2>/dev/null; then
  echo "--- Build Check ---"
  if npm run build --silent 2>&1 | tail -5; then
    BUILD_STATUS="Clean"
  else
    BUILD_STATUS="Failed (see logs)"
  fi
fi

# Check npm audit if applicable
AUDIT_STATUS=""
if [ -f "${ROOT}/package-lock.json" ]; then
  echo "--- Security Audit ---"
  AUDIT_OUT=$(npm audit 2>&1 || true)
  if echo "$AUDIT_OUT" | grep -q "found 0 vulnerabilities"; then
    AUDIT_STATUS="0 vulnerabilities"
  else
    AUDIT_STATUS=$(echo "$AUDIT_OUT" | grep -oE 'found [0-9]+ vulnerabilit.*' | head -1 || echo "See audit output")
  fi
fi

# ─── Collect light sprint metrics ────────────────────────────────────────────
# Quick, relevant metrics that help plan the next sprint. No LLM needed.
# Captures: sprint git diff, test health, build/audit status.

# Git stats for this sprint (diff from previous sprint)
SPRINT_DIFF=""
prev_sprint=$((SPRINT_NUM - 1))
base_sha=$(git log --oneline --first-parent main -200 2>/dev/null | \
  grep -i -m1 "sprint.*${prev_sprint}.*status\|Sprint ${prev_sprint}" | awk '{print $1}' || true)
if [ -n "$base_sha" ]; then
  SPRINT_DIFF=$(git diff --shortstat "${base_sha}..HEAD" 2>/dev/null || echo "")
fi

# Test file count
TEST_FILE_COUNT=$(find "${ROOT}" -name '*.test.*' -o -name '*.spec.*' \
  -not -path '*/node_modules/*' -not -path '*/.next/*' -not -path '*/build/*' \
  2>/dev/null | wc -l | tr -d ' ')

echo ""
echo "=== Sprint Metrics ==="
echo "  Agents: ${TOTAL}"
[ -n "$TEST_COUNT" ] && echo "  Tests: ${TEST_COUNT}"
echo "  Test files: ${TEST_FILE_COUNT}"
[ -n "$BUILD_STATUS" ] && echo "  Build: ${BUILD_STATUS}"
[ -n "$AUDIT_STATUS" ] && echo "  Audit: ${AUDIT_STATUS}"
[ -n "$SPRINT_DIFF" ] && echo "  Diff: ${SPRINT_DIFF}"

# ─── Auto-generate PROJECT_STATUS ─────────────────────────────────────────────
# Uses the sprint brief + merge results + light metrics to produce a status doc.

STATUS_DATE=$(date -u +%Y-%-m-%-d)
STATUS_DATE_DISPLAY=$(date -u +"%B %-d, %Y")
STATUS_FILE="${ROOT}/docs/PROJECT_STATUS_${STATUS_DATE}-sprint${SPRINT_NUM}.md"

# Extract sprint title from SPRINT_BRIEF.md heading (e.g., "# Sprint 4: Signals Dashboard")
SPRINT_TITLE=$(grep -m1 '^# Sprint ' "$BRIEF_FILE" | sed -E 's/^# Sprint [0-9]+[: —-]*//')
if [ -z "$SPRINT_TITLE" ]; then
  SPRINT_TITLE="Sprint ${SPRINT_NUM}"
fi

# Extract all goal lines from meta block
SPRINT_GOAL=$(echo "$SPRINT_META" | awk '
  /^Goal/ { found=1; next }
  /^[A-Z]/ { if (found) exit }
  found && /[^ ]/ { print }
')
if [ -z "$SPRINT_GOAL" ]; then
  SPRINT_GOAL="Sprint ${SPRINT_NUM} completed."
fi

# Build "What Changed" sections from agent objectives + actual commits + file stats
WHAT_CHANGED=""
for agent in "${ACTIVE_MERGE[@]}"; do
  # Extract objective from agent's brief section
  objective=$(get_agent_brief "$agent" | awk '
    /^Objective/ { found=1; next }
    /^[A-Z]/ { if (found) exit }
    found && /[^ ]/ { print }
  ')
  if [ -z "$objective" ]; then
    objective="Completed assigned tasks."
  fi

  # Format commits as bullet list
  commits_block=""
  if [ -f "${MERGE_DATA_DIR}/${agent}.commits" ] && [ -s "${MERGE_DATA_DIR}/${agent}.commits" ]; then
    while IFS= read -r cline; do
      [ -z "$cline" ] && continue
      # Strip commit hash prefix, keep subject
      subject=$(echo "$cline" | sed 's/^[a-f0-9]* //')
      commits_block="${commits_block}- ${subject}
"
    done < "${MERGE_DATA_DIR}/${agent}.commits"
  fi
  if [ -z "$commits_block" ]; then
    commits_block="- (no commits)
"
  fi

  # Format file stats
  file_stats="no changes"
  if [ -f "${MERGE_DATA_DIR}/${agent}.stats" ] && [ -s "${MERGE_DATA_DIR}/${agent}.stats" ]; then
    file_stats=$(cat "${MERGE_DATA_DIR}/${agent}.stats")
  fi

  WHAT_CHANGED="${WHAT_CHANGED}### ${agent}

${objective}

**Commits:**
${commits_block}
**Files:** ${file_stats}

"
done

# Build agent merge table rows with deliverables, real conflict status, and file counts
AGENT_TABLE=""
AGENT_NUM=0
for agent in "${ACTIVE_MERGE[@]}"; do
  AGENT_NUM=$((AGENT_NUM + 1))
  phase=$(get_agent_phase "$agent")
  # Extract first objective line as deliverable
  deliverable=$(get_agent_brief "$agent" | awk '
    /^Objective/ { found=1; next }
    /^[A-Z]/ { if (found) exit }
    found && /[^ ]/ { sub(/^- /, ""); print; exit }
  ')
  if [ -z "$deliverable" ]; then
    deliverable="Completed tasks"
  fi
  conflict_status="Clean"
  if [ -f "${MERGE_DATA_DIR}/${agent}.conflict" ]; then
    conflict_status=$(cat "${MERGE_DATA_DIR}/${agent}.conflict")
  fi
  # Extract file count from diffstat (e.g., " 4 files changed, 495 insertions(+), 48 deletions(-)")
  agent_stats=""
  if [ -f "${MERGE_DATA_DIR}/${agent}.stats" ]; then
    agent_stats=$(cat "${MERGE_DATA_DIR}/${agent}.stats")
  fi
  file_count=$(echo "$agent_stats" | grep -oE '[0-9]+ files? changed' | grep -oE '[0-9]+' || echo "0")
  AGENT_TABLE="${AGENT_TABLE}| ${AGENT_NUM} | ${agent} | ${deliverable} | ${phase} | ${conflict_status} | ${file_count} |
"
done

# Extract next steps from sprint brief if present
NEXT_STEPS=$(echo "$SPRINT_META" | awk '
  /^Next Steps/ || /^Next/ { found=1; next }
  /^[A-Z]/ { if (found) exit }
  found && /^-/ { print }
')
if [ -z "$NEXT_STEPS" ]; then
  NEXT_STEPS="- Review sprint output and plan next sprint"
fi

# Build sprint metrics section (light — just the numbers that matter)
METRICS_SECTION="## Sprint Metrics

| Metric | Value |
|--------|-------|
| Agents | ${TOTAL} |
"
[ -n "$TEST_COUNT" ] && METRICS_SECTION="${METRICS_SECTION}| Tests | ${TEST_COUNT} |
"
METRICS_SECTION="${METRICS_SECTION}| Test files | ${TEST_FILE_COUNT} |
"
[ -n "$BUILD_STATUS" ] && METRICS_SECTION="${METRICS_SECTION}| Build | ${BUILD_STATUS} |
"
[ -n "$AUDIT_STATUS" ] && METRICS_SECTION="${METRICS_SECTION}| Security audit | ${AUDIT_STATUS} |
"
[ -n "$SPRINT_DIFF" ] && METRICS_SECTION="${METRICS_SECTION}| Git diff | ${SPRINT_DIFF} |
"
METRICS_SECTION="${METRICS_SECTION}
---

"

# Build backlog snapshot if backlog/README.md exists
BACKLOG_SNAPSHOT=""
BACKLOG_FILE="${ROOT}/docs/project-memory/backlog/README.md"
if [ -f "$BACKLOG_FILE" ]; then
  # Extract completed items (status contains "Complete" or "Fixed")
  completed=$(grep -E '\|.*\|.*(Complete|Fixed)' "$BACKLOG_FILE" | sed 's/^|[[:space:]]*/- /' | sed 's/[[:space:]]*|.*//' || true)
  # Extract open high-priority items (status does NOT contain Complete/Fixed)
  open_items=$(grep -E '\|.*\|.*(Critical|High)' "$BACKLOG_FILE" | grep -vE '(Complete|Fixed)' | sed 's/^|[[:space:]]*/- /' | sed 's/[[:space:]]*|.*//' || true)
  # Count all open items
  open_bug_count=$(grep -cE '^\| *B-.*\| *Open' "$BACKLOG_FILE" 2>/dev/null || echo "0")
  open_feature_count=$(grep -cE '^\| *F-.*\| *Open' "$BACKLOG_FILE" 2>/dev/null || echo "0")

  if [ -n "$completed" ] || [ -n "$open_items" ] || [ "$open_bug_count" -gt 0 ] || [ "$open_feature_count" -gt 0 ]; then
    BACKLOG_SNAPSHOT="## Backlog Snapshot

**Open:** ${open_bug_count} bug(s), ${open_feature_count} feature request(s)

"
    if [ -n "$open_items" ]; then
      BACKLOG_SNAPSHOT="${BACKLOG_SNAPSHOT}### High Priority (Open)
${open_items}

"
    fi
    if [ -n "$completed" ]; then
      BACKLOG_SNAPSHOT="${BACKLOG_SNAPSHOT}### Completed This Sprint
${completed}

"
    fi
    BACKLOG_SNAPSHOT="${BACKLOG_SNAPSHOT}---

"
  fi
fi

mkdir -p "${ROOT}/docs"

REPO_NAME=$(basename "${ROOT}")

cat > "$STATUS_FILE" << STATUSEOF
# ${REPO_NAME} Project Status — ${STATUS_DATE_DISPLAY} (Sprint ${SPRINT_NUM}: ${SPRINT_TITLE})

## Sprint ${SPRINT_NUM} Summary

${SPRINT_GOAL}

---

## What Changed

${WHAT_CHANGED}
---

## Merge Results

| # | Branch | Deliverable | Phase | Conflicts | Files Changed |
|---|--------|-------------|-------|-----------|---------------|
${AGENT_TABLE}
---

${METRICS_SECTION}${BACKLOG_SNAPSHOT}## Next Steps

${NEXT_STEPS}
STATUSEOF

echo ""
echo "=== PROJECT_STATUS doc generated ==="
echo "  ${STATUS_FILE}"

# ─── Auto-rebuild Afterburner dashboard data ──────────────────────────────────
# Calls the dashboard's rebuild API (port 1201) so sprint data is immediately
# visible without a manual rebuild step. Non-fatal — skips silently if server
# is not running.
_REBUILD_PAYLOAD="{\"projectRoot\":\"${ROOT}\",\"slug\":\"${_SLUG}\"}"
if curl -s -X POST http://localhost:1201/api/rebuild-data \
     -H 'Content-Type: application/json' \
     -d "$_REBUILD_PAYLOAD" \
     --connect-timeout 2 --max-time 10 \
     -o /dev/null 2>/dev/null; then
  echo "=== Dashboard data rebuilt (${_SLUG}) ==="
else
  echo "=== Dashboard rebuild skipped (server not running on :1201) ==="
fi

# ─── Update roadmap "You are here" sprint marker ─────────────────────────────
# The dashboard's roadmap view parses "You are here: Sprint N" from ROADMAP*.md
# to render the "⚡ You are here" banner. Update the sprint number in-place so
# the roadmap always reflects the latest completed sprint without manual edits.
_ROADMAP_UPDATED=0
for _rm in "${ROOT}"/docs/lifecycle/ROADMAP*.md; do
  if [ -f "$_rm" ] && grep -q "You are here:" "$_rm" 2>/dev/null; then
    sed -i.bak "s/You are here: Sprint *[0-9]*/You are here: Sprint ${SPRINT_NUM}/" "$_rm" \
      && rm -f "${_rm}.bak"
    echo "=== Roadmap updated: 'You are here → Sprint ${SPRINT_NUM}' in $(basename "$_rm") ==="
    _ROADMAP_UPDATED=$((_ROADMAP_UPDATED + 1))
  fi
done
[ "$_ROADMAP_UPDATED" -eq 0 ] && echo "=== No roadmap 'You are here' marker found (skipped) ==="

# ─── Write sprint number to .sprint/sprint-number ────────────────────────────
# Single authoritative source for the current sprint number.
# Plain integer — trivial to write, trivial to read, impossible to corrupt.
echo "$SPRINT_NUM" > "${ROOT}/.sprint/sprint-number"
echo "=== Sprint number recorded: ${SPRINT_NUM} (.sprint/sprint-number) ==="

# ─── Post-merge hooks ────────────────────────────────────────────────────────
# Run hooks unless --skip-hooks was passed (e.g., by sprint-run.sh which runs
# hooks itself at the end of its pipeline, after LLM report generation).
if ! $SKIP_HOOKS && [ ${#POST_MERGE_HOOKS[@]} -gt 0 ]; then
  echo ""
  echo "=== Running post-merge hooks ==="
  for hook in "${POST_MERGE_HOOKS[@]}"; do
    echo "  Running: ${hook}"
    if (
      export SPRINT_NUM ROOT STATUS_FILE SPRINT_BASE
      eval "$hook"
    ) 2>&1; then
      echo "  [ok] ${hook}"
    else
      echo "  [warn] Hook failed: ${hook} — continuing"
    fi
  done
fi

# Output the status file path on the last line — callers can capture this
echo "STATUS_FILE=${STATUS_FILE}"
